/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisplayTokenRouteImport } from './routes/display.$token'
import { Route as AppWinesRouteImport } from './routes/_app.wines'
import { Route as AppRecipesRouteImport } from './routes/_app.recipes'
import { Route as AppOpenCloseRouteImport } from './routes/_app.open-close'
import { Route as AppMenuFormattingRouteImport } from './routes/_app.menu-formatting'
import { Route as AppMenuEditorRouteImport } from './routes/_app.menu-editor'
import { Route as AppLiveMenuTimetableRouteImport } from './routes/_app.live-menu-timetable'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppFunctionsRouteImport } from './routes/_app.functions'
import { Route as AppEventsRouteImport } from './routes/_app.events'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as ApiPublicWebhookRouteImport } from './routes/api/public/webhook'
import { Route as ApiPublicMenuRefreshRouteImport } from './routes/api/public/menu-refresh'
import { Route as ApiPublicJotformEventInquiryRouteImport } from './routes/api/public/jotform-event-inquiry'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayTokenRoute = DisplayTokenRouteImport.update({
  id: '/display/$token',
  path: '/display/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWinesRoute = AppWinesRouteImport.update({
  id: '/wines',
  path: '/wines',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRoute = AppRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AppRoute,
} as any)
const AppOpenCloseRoute = AppOpenCloseRouteImport.update({
  id: '/open-close',
  path: '/open-close',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuFormattingRoute = AppMenuFormattingRouteImport.update({
  id: '/menu-formatting',
  path: '/menu-formatting',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuEditorRoute = AppMenuEditorRouteImport.update({
  id: '/menu-editor',
  path: '/menu-editor',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveMenuTimetableRoute = AppLiveMenuTimetableRouteImport.update({
  id: '/live-menu-timetable',
  path: '/live-menu-timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppFunctionsRoute = AppFunctionsRouteImport.update({
  id: '/functions',
  path: '/functions',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicWebhookRoute = ApiPublicWebhookRouteImport.update({
  id: '/api/public/webhook',
  path: '/api/public/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMenuRefreshRoute = ApiPublicMenuRefreshRouteImport.update({
  id: '/api/public/menu-refresh',
  path: '/api/public/menu-refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJotformEventInquiryRoute =
  ApiPublicJotformEventInquiryRouteImport.update({
    id: '/api/public/jotform-event-inquiry',
    path: '/api/public/jotform-event-inquiry',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/events': typeof AppEventsRoute
  '/functions': typeof AppFunctionsRoute
  '/home': typeof AppHomeRoute
  '/live-menu-timetable': typeof AppLiveMenuTimetableRoute
  '/menu-editor': typeof AppMenuEditorRoute
  '/menu-formatting': typeof AppMenuFormattingRoute
  '/open-close': typeof AppOpenCloseRoute
  '/recipes': typeof AppRecipesRoute
  '/wines': typeof AppWinesRoute
  '/display/$token': typeof DisplayTokenRoute
  '/api/public/jotform-event-inquiry': typeof ApiPublicJotformEventInquiryRoute
  '/api/public/menu-refresh': typeof ApiPublicMenuRefreshRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/events': typeof AppEventsRoute
  '/functions': typeof AppFunctionsRoute
  '/home': typeof AppHomeRoute
  '/live-menu-timetable': typeof AppLiveMenuTimetableRoute
  '/menu-editor': typeof AppMenuEditorRoute
  '/menu-formatting': typeof AppMenuFormattingRoute
  '/open-close': typeof AppOpenCloseRoute
  '/recipes': typeof AppRecipesRoute
  '/wines': typeof AppWinesRoute
  '/display/$token': typeof DisplayTokenRoute
  '/api/public/jotform-event-inquiry': typeof ApiPublicJotformEventInquiryRoute
  '/api/public/menu-refresh': typeof ApiPublicMenuRefreshRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/functions': typeof AppFunctionsRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/live-menu-timetable': typeof AppLiveMenuTimetableRoute
  '/_app/menu-editor': typeof AppMenuEditorRoute
  '/_app/menu-formatting': typeof AppMenuFormattingRoute
  '/_app/open-close': typeof AppOpenCloseRoute
  '/_app/recipes': typeof AppRecipesRoute
  '/_app/wines': typeof AppWinesRoute
  '/display/$token': typeof DisplayTokenRoute
  '/api/public/jotform-event-inquiry': typeof ApiPublicJotformEventInquiryRoute
  '/api/public/menu-refresh': typeof ApiPublicMenuRefreshRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/events'
    | '/functions'
    | '/home'
    | '/live-menu-timetable'
    | '/menu-editor'
    | '/menu-formatting'
    | '/open-close'
    | '/recipes'
    | '/wines'
    | '/display/$token'
    | '/api/public/jotform-event-inquiry'
    | '/api/public/menu-refresh'
    | '/api/public/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/events'
    | '/functions'
    | '/home'
    | '/live-menu-timetable'
    | '/menu-editor'
    | '/menu-formatting'
    | '/open-close'
    | '/recipes'
    | '/wines'
    | '/display/$token'
    | '/api/public/jotform-event-inquiry'
    | '/api/public/menu-refresh'
    | '/api/public/webhook'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/admin'
    | '/_app/events'
    | '/_app/functions'
    | '/_app/home'
    | '/_app/live-menu-timetable'
    | '/_app/menu-editor'
    | '/_app/menu-formatting'
    | '/_app/open-close'
    | '/_app/recipes'
    | '/_app/wines'
    | '/display/$token'
    | '/api/public/jotform-event-inquiry'
    | '/api/public/menu-refresh'
    | '/api/public/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DisplayTokenRoute: typeof DisplayTokenRoute
  ApiPublicJotformEventInquiryRoute: typeof ApiPublicJotformEventInquiryRoute
  ApiPublicMenuRefreshRoute: typeof ApiPublicMenuRefreshRoute
  ApiPublicWebhookRoute: typeof ApiPublicWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display/$token': {
      id: '/display/$token'
      path: '/display/$token'
      fullPath: '/display/$token'
      preLoaderRoute: typeof DisplayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wines': {
      id: '/_app/wines'
      path: '/wines'
      fullPath: '/wines'
      preLoaderRoute: typeof AppWinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes': {
      id: '/_app/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AppRecipesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/open-close': {
      id: '/_app/open-close'
      path: '/open-close'
      fullPath: '/open-close'
      preLoaderRoute: typeof AppOpenCloseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu-formatting': {
      id: '/_app/menu-formatting'
      path: '/menu-formatting'
      fullPath: '/menu-formatting'
      preLoaderRoute: typeof AppMenuFormattingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu-editor': {
      id: '/_app/menu-editor'
      path: '/menu-editor'
      fullPath: '/menu-editor'
      preLoaderRoute: typeof AppMenuEditorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live-menu-timetable': {
      id: '/_app/live-menu-timetable'
      path: '/live-menu-timetable'
      fullPath: '/live-menu-timetable'
      preLoaderRoute: typeof AppLiveMenuTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/functions': {
      id: '/_app/functions'
      path: '/functions'
      fullPath: '/functions'
      preLoaderRoute: typeof AppFunctionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/webhook': {
      id: '/api/public/webhook'
      path: '/api/public/webhook'
      fullPath: '/api/public/webhook'
      preLoaderRoute: typeof ApiPublicWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/menu-refresh': {
      id: '/api/public/menu-refresh'
      path: '/api/public/menu-refresh'
      fullPath: '/api/public/menu-refresh'
      preLoaderRoute: typeof ApiPublicMenuRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jotform-event-inquiry': {
      id: '/api/public/jotform-event-inquiry'
      path: '/api/public/jotform-event-inquiry'
      fullPath: '/api/public/jotform-event-inquiry'
      preLoaderRoute: typeof ApiPublicJotformEventInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppEventsRoute: typeof AppEventsRoute
  AppFunctionsRoute: typeof AppFunctionsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppLiveMenuTimetableRoute: typeof AppLiveMenuTimetableRoute
  AppMenuEditorRoute: typeof AppMenuEditorRoute
  AppMenuFormattingRoute: typeof AppMenuFormattingRoute
  AppOpenCloseRoute: typeof AppOpenCloseRoute
  AppRecipesRoute: typeof AppRecipesRoute
  AppWinesRoute: typeof AppWinesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppEventsRoute: AppEventsRoute,
  AppFunctionsRoute: AppFunctionsRoute,
  AppHomeRoute: AppHomeRoute,
  AppLiveMenuTimetableRoute: AppLiveMenuTimetableRoute,
  AppMenuEditorRoute: AppMenuEditorRoute,
  AppMenuFormattingRoute: AppMenuFormattingRoute,
  AppOpenCloseRoute: AppOpenCloseRoute,
  AppRecipesRoute: AppRecipesRoute,
  AppWinesRoute: AppWinesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DisplayTokenRoute: DisplayTokenRoute,
  ApiPublicJotformEventInquiryRoute: ApiPublicJotformEventInquiryRoute,
  ApiPublicMenuRefreshRoute: ApiPublicMenuRefreshRoute,
  ApiPublicWebhookRoute: ApiPublicWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
